import os
import json
from datetime import datetime
from fpdf import FPDF
from config.settings import REPORT_DIR

class OSINTReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_fill_color(13, 13, 13)
        self.set_text_color(0, 255, 255)
        self.cell(0, 10, "OSINTool - Intelligence Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Generated by OSINTool v2.0 | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", align="C")

def generate_pdf(data, risk_data=None):
    os.makedirs(REPORT_DIR, exist_ok=True)

    target = data.get("target", "unknown").replace(".", "_").replace("@", "_at_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{REPORT_DIR}/{target}_{timestamp}.pdf"

    pdf = OSINTReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(0, 200, 200)
    pdf.cell(0, 15, "OSINT Investigation Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Target Info
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(255, 200, 0)
    pdf.cell(0, 8, f"Target: {data.get('target')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Type: {data.get('type', 'N/A').upper()}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Risk Score
    if risk_data:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(255, 50, 50)
        pdf.cell(0, 10, f"Risk Score: {risk_data['score']}/100 - {risk_data['level']}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        for item in risk_data.get("breakdown", []):
            pdf.cell(0, 7, f"  - {item}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

    # Full Data
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 150, 200)
    pdf.cell(0, 10, "Full Investigation Data:", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Courier", "", 8)
    pdf.set_text_color(30, 30, 30)

    json_text = json.dumps(data, indent=2, default=str)
    for line in json_text.splitlines():
        try:
            pdf.cell(0, 5, line[:120], new_x="LMARGIN", new_y="NEXT")
        except:
            pass

    pdf.output(filename)
    return filename
